layout_spectrum: 0.274459341308102
typography_spectrum: 0.3260023598559201
color:
  brandStrength: 0.6530180287081748
  lightness: 0.9525942308828235
  saturation: 0.3943403016310185
  rhythmicContrast: 0.08400481985881925
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
name: Hawaii Perfect
navigation:
  - id: 'http://hawaiiperfect.com'
    url: 'http://hawaiiperfect.com'
    name: Let us worry about the details for you
    type: external
  - id: >-
      http://www.smartdestinations.com/oahu-attractions-and-tours/_d_Hio-p1.html?pass=Hio_Prod_Go&gclid=CjwKEAjw_LG8BRDb1JTxm8uP_UwSJADu_8pWd8HQnhiCyWDksngJ3zA_spplqEphZkwzwd0EMPXj0RoC9ajw_wcB
    url: >-
      http://www.smartdestinations.com/oahu-attractions-and-tours/_d_Hio-p1.html?pass=Hio_Prod_Go&gclid=CjwKEAjw_LG8BRDb1JTxm8uP_UwSJADu_8pWd8HQnhiCyWDksngJ3zA_spplqEphZkwzwd0EMPXj0RoC9ajw_wcB
    name: A tip to some Island entertainment
    type: external
